FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
COPY shared/package*.json ./shared/

RUN npm install

COPY shared/ ./shared/
COPY server/ ./server/

CMD ["npm", "run", "dev", "-w", "server"]